app.miniapp.url = http://localhost:${application.nosliw-static.port}/data/main/application/application.html


application.nosliw-datasource.port = 8085
application.nosliw-datasource.name = datasource
application.nosliw-datasource.baseurl = http://${application.nosliw-datasource.name}:${application.nosliw-datasource.port}/nosliw/datasource/

application.nosliw-static.port = 8081
application.nosliw-static.name = static
application.nosliw-static.baseurl = http://${application.nosliw-static.name}:${application.nosliw-static.port}/nosliw/static/
application.nosliw-static.static.url = http://localhost:8081/static/
application.nosliw-static.temporary.path = C:/Temp/nosliw/temp/
application.nosliw-static.temporary.url = http://localhost:8081/temp/


application.nosliw-core.port = 8080
application.nosliw-core.name = core
application.nosliw-core.baseurl = http://${application.nosliw-core.name}:${application.nosliw-core.port}/nosliw/core/

application.nosliw-story.port = 8083
application.nosliw-story.name = story
application.nosliw-story.baseurl = http://${application.nosliw-story.name}:${application.nosliw-story.port}/nosliw/story/
application.nosliw-story.persistence.path = file:///C:/Temp/nosliw/data/storydesign

uitag.definition-path = file:///C:/Mywork/Library/uitag
codetable.data-path = file:///C:/Mywork/Library/codetable
script.definition-path = file:///C:/Mywork/Library/script
configure.data-path = file:///C:/Mywork/Library/configure
taskinterface.path = file:///C:/Mywork/Library/serviceinterface

division.script.definition-path = file:///C:/Mywork/Library/brick_definition/script

division.manual.definition-path = file:///C:/Mywork/Library/brick_definition/manual
division.manual.execute-path = file:///C:Temp/nosliw/temp/manualbundleexport

runtime.rhino.script-export-path = file:///C:/Temp/nosliw/temp/scriptexport/scripts

core.bundle.export-path = file:///C:/Temp/nosliw/temp/bundleexport



# Database authentication credentials
spring.datasource.username=admin
spring.datasource.password=admin
#spring.datasource.password=tony0818

# Optional: Spring Boot usually auto-detects this based on the URL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.address = localhost
#spring.datasource.address = db-core.cbuqogwi0wb5.ca-central-1.rds.amazonaws.com
spring.datasource.address = localhost
spring.datasource.url: jdbc:mysql://${spring.datasource.address}/nosliw?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true

# Resource
resource.cached=false
resource.file-load-mode = never
resource.file-load-resources = "script","uiModuleDecoration","uipage","activityPlugin","uiTag","script","decoration_script","uitagscript", "converter", "operation"

