application.nosliw-datasource.port = 8085
application.nosliw-datasource.name = datasource
application.nosliw-datasource.baseurl = http://${application.nosliw-datasource.name}:${application.nosliw-datasource.port}/nosliw/datasource


application.nosliw-core.port = 8080
application.nosliw-core.name = core



# Database authentication credentials
spring.datasource.username=admin
spring.datasource.password=admin

# Optional: Spring Boot usually auto-detects this based on the URL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost/nosliw?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true


